# Generated by Django 3.0.1 on 2021-08-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(auto_now_add=True)),
                ('reward', models.CharField(max_length=30)),
                ('value', models.CharField(default='', max_length=30)),
                ('Challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wevents.Challenge')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wevents.Tier')),
            ],
        ),
    ]
