# Generated by Django 3.0.1 on 2021-08-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wevents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyevents',
            name='event_date',
        ),
    ]
