# Generated by Django 3.0.1 on 2021-08-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevents', '0003_weeklyevents_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyevents',
            name='event_date',
            field=models.DateField(),
        ),
    ]
