# Generated by Django 3.0.1 on 2021-08-26 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wevents', '0004_auto_20210822_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='weeklyevents',
            name='Challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='wevents.Challenge'),
        ),
        migrations.AlterField(
            model_name='weeklyevents',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='wevents.Tier'),
        ),
    ]
