# Generated by Django 3.0.1 on 2021-08-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wevents', '0005_auto_20210826_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leaderboard',
        ),
    ]
